[package]
name = "dsc-commands-remover"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
poise = "0.5"
tokio = { version = "1", features = ["full"] }
